[tool.taskipy.tasks]
[tool.taskipy.tasks.index]
cmd = "python scripts/generate_index.py"
help = "Update index.html file."

[tool.taskipy.tasks.presentation]
cmd = "python scripts/generate_presentation.py"
help = "Criate new presentation."

[tool.taskipy.tasks.container]
cmd = """
  echo 'Ligando servidor na porta 8001' &&
	docker run -it --rm -p 8001:8000 \
		-v /$PWD/presentations:/reveal.js/presentations \
		-v /$PWD/dist:/reveal.js/dist \
		-v $PWD/index.html:/reveal.js/index.html \
		-v $PWD/media:/reveal.js/media \
		-v $PWD/css:/reveal.js/css \
		-v $PWD/plugin:/reveal.js/plugin nbrown/revealjs
"""
help = "Starts docker container and local server."
